### ISSUE TITLE
Page to view test scores.

### ISSUE THREAD

**Issue by aavishkarmishra** [Manthan933/Manthan#18]
### Create a page to view scores
Test object have a scores array having object with student's email and score, please create a page so that instructors can view the scores of students.

Features required :
- Scores can be sorted 
- Scores can be edited
- Responsive design 

**Additional context**
Please use **materialUI** instead of bootstrap or react bootstrap.

**Comment by pritamp17** [comment]
@aavishkarmishra could you assign this to me?

**Comment by deepthiteki** [comment]
Hey @aavishkarmishra 
Can I work on this issue under GSSOC'21

**Comment by aavishkarmishra** [comment]
Yes please proceed and ping me if anything is required from my side.

**Comment by Muditxofficial** [comment]
@aavishkarmishra Can you assign this to me if anybody not working on this.

**Comment by tend2infinity** [comment]
I would like to work on this issue, if anyone is already working on it, I would love to collaborate with that guy!

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by tend2infinity** [comment]
@aavishkarmishra, First of all, sorry for the delay that I've made in getting back to this issue, there were some personal issues. Now, see right now in this project a user can give a test any number of times, and just because of that a single user can have many different scores. So, I feel that to make a scores page, we need to ensure that a single user can give the test only once. I will create a pull request for this issue

**Comment by AADITYA-SINGH497** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by subhangi2731** [comment]
assign me this please
