### ISSUE TITLE
Logo is not loading

### ISSUE THREAD

**Issue by yogi2103** [Manthan933/Manthan#226]
**Describe the bug**
Logo is not loading on the url "https://github.com/Manthan933/Manthan/wiki"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prudhvirajstark** [comment]
Hello,

@aavishkarmishra The root cause of the bug comes from _Footer file in Manthan.wiki

In the below line, the image(Method Draw Image.png) is Missing or not found. 

 --    ![Manthan Logo](https://github.com/aavishkarmishra/Manthan/blob/main/Method%20Draw%20Image.png)

## Work Arounds
 --    Add the Image logo (image) in the profile(aavishkarmishra) inside Manthan folder
### Or
 --    Add the logo into the Manthan933 inside Manthan folder profile as below
Example:-
![Manthan Logo](https://github.com/Manthan933/Manthan/blob/main/image-in-readme.png)

Thanks,
Prudhvi raj

**Comment by yogi2103** [comment]
Even the images uploaded by @prudhvirajstark are not visible itself here.
